extends: airbnb-base

env:
  browser: false
  node: true
  "jest/globals": true

rules:
  "no-underscore-dangle": off
  "no-console": off
  "no-await-in-loop": off
  "no-restricted-syntax": off
  "object-curly-newline":
    - error
    - multiline: true
      consistent: true

plugins:
  - jest