extends:
  - airbnb-base
  - plugin:sonarjs/recommended

env:
  browser: false
  node: true
  "jest/globals": true

rules:
  "no-underscore-dangle": off
  "no-console": off
  "no-await-in-loop": off
  "no-restricted-syntax": off
  "object-curly-newline":
    - error
    - multiline: true
      consistent: true
  "max-lines-per-function":
    - error
    - max: 25
      skipComments: true
      skipBlankLines: true
  "max-depth":
    - error
    - max: 2
  "max-lines":
    - error
    - max: 200
  "max-nested-callbacks":
    - error
    - max: 2
  "max-params":
    - error
    - max: 4
  "max-statements":
    - error
    - max: 20
  "max-statements-per-line":
    - error
    - max: 1
  "sonarjs/cognitive-complexity":
    - error
    - 5

plugins:
  - jest
  - sonarjs