language: node_js
node_js:
  - "10.11"


jobs:
  include:
    - stage: test
      name: Units and integration tests
      script: npm test

    - stage: test
      name: Security tests
      script: npm audit
