language: node_js
node_js:
  - "10.11"

env:
  global:
    - YARN_VERSION="1.12.3"

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version ${YARN_VERSION}
  - export PATH="$HOME/.yarn/bin:$PATH"

jobs:
  include:
    - stage: test
      name: Linting
      script: yarn run lint

    - stage: test
      name: Units and integration tests
      script: yarn test

    - stage: test
      name: Security tests
      script: yarn audit

    - stage: deploy
      if: tag IS present
      script: skip
      deploy:
        skip_cleanup: true
        provider: script
        script: yarn run ci-release
        on:
          tags: true
